### PR TITLE
DM-6824: Use meas.algorithms.astrometrySourceSelector in measOptimisticB

### PR DESCRIPTION
**Pull request by morriscb**
Added compliance with the new sourceSelector object in meas_astrom/matchOptimisticB as part of tickets/DM-6824. This required a small change to how HSC specific parameters were set in config/hsc/processCdd.py

### CODE REVIEW

**Comment by parejkoj** [comment]
This looks ok to me, if it works, but we should check with @PaulPrice for details. Also, please squash those two commits together.

**Comment by PaulPrice** [comment]
Fine with me so long as this goes through ci_hsc.

**Comment by parejkoj** [comment]
Good point: @morriscb please run jenkins on this branch with ci_hsc.

**Comment by morriscb** [comment]
Already done and it does pass ci_hsc.

**Comment by parejkoj** [comment]
Sounds good!

**Pull request merged**
