### PR TITLE
DM-20574: Remove deprecated isr.doAddDistortionModel option.

### PR DESCRIPTION
**Pull request by czwa**

### CODE REVIEW

**Comment by czwa** [comment]
Closing PR as `addDistortionModel` should be retained _through_ v19.

**Comment by timj** [comment]
Note that in less than a month this change could be reapplied.

**Comment by timj** [comment]
(also, why are these PRs showing that they are merged but also not in MERGED state but instead in CLOSED).

**Comment by czwa** [comment]
My "look on the bright side" thought was that I have a very good idea of what needs to happen for the next deprecation in ip_isr+obs.
The closed vs merged thing is something github decided when I pushed the deletion of the commits.  I double checked that doAddDistortionModel was still there on master, and moved on.

**Pull request closed without merging**
